-- telescope options

return {
  require("telescope").setup({
    defaults = {
      theme = "ivy",
      bottom_pane = { height = 10 },
    },
    pickers = {
      find_files = { theme = "ivy" },
      git_files = { theme = "ivy" },
      grep_string = { theme = "ivy" },
      live_grep = { theme = "ivy" },
      buffers = { theme = "ivy" },
      oldfiles = { theme = "ivy" },
      commands = { theme = "ivy" },
      tags = { theme = "ivy" },
      command_history = { theme = "ivy" },
      search_history = { theme = "ivy" },
      help_tags = { theme = "ivy" },
      man_pages = { theme = "ivy" },
      marks = { theme = "ivy" },
      colorshceme = { theme = "ivy" },
      quickfix = { theme = "ivy" },
      quickfixhistory = { theme = "ivy" },
      loclist = { theme = "ivy" },
      jumplist = { theme = "ivy" },
      vim_options = { theme = "ivy" },
      registers = { theme = "ivy" },
      autocommands = { theme = "ivy" },
      spell_suggest = { theme = "ivy" },
      keymaps = { theme = "ivy" },
      filetypes = { theme = "ivy" },
      highlights = { theme = "ivy" },
      current_buffer_fuzzy_find = { theme = "ivy" },
      current_buffer_tags = { theme = "ivy" },
      resume = { theme = "ivy" },
      pickers = { theme = "ivy" },
      lsp_references = { theme = "ivy" },
      lsp_incominc_calls = { theme = "ivy" },
      lsp_outgoing_calls = { theme = "ivy" },
      lsp_document_symbols = { theme = "ivy" },
      lsp_workplace_symbols = { theme = "ivy" },
      lsp_dynamic_workspace_symbols = { theme = "ivy" },
      diagnostics = { theme = "ivy" },
      lsp_implementations = { theme = "ivy" },
      lsp_definitions = { theme = "ivy" },
      lsp_type_definitions = { theme = "ivy" },
      git_commits = { theme = "ivy" },
      git_bcommits = { theme = "ivy" },
      git_bcommits_range = { theme = "ivy" },
      git_branches = { theme = "ivy" },
      git_status = { theme = "ivy" },
      git_stash = { theme = "ivy" },
      treesitter = { theme = "ivy" },
      builtin = { theme = "ivy" },
      reloader = { theme = "ivy" },
      symbols = { theme = "ivy" },
    },
  }),
}
